### PR TITLE
Gradle for building and distributing

### LINKED ISSUE #6: Release will not run on windows 10
The release exe will not run on windows 10.

### PR DESCRIPTION
**Pull request by pupper68k**
[In Progress]

I noticed in #10  that you did not have instructions to build this project in your readme.
I spent a bit of time modifying the codebase and have managed to refactor it into using the Gradle build system.

This has a number of benefits:
- no longer need NetBeans to build project
- easy to get gradle to output a distributable jar
- much easier to automate build process, now we can use CI/CD
- no longer need to commit compiled binaries to codebase, anyone can run gradle build
- gradle can manage the dependancies
- gradle can handle the installation process.

Things I have done:
- gradle builds project into a runnable jar
- gradle can run the project
- gradle is tracking dependancies

Things I will have done soon:
- gradle can handle installation of the application into the system.

This PR will fix #6 #10 and #7

### CODE REVIEW

**Comment by pupper68k** [comment]
There is now a system installation script for Linux users and directions for windows users.

Let me know if you are interested in further changes or if you would rather not integrate these changes.

**Comment by abdalmoniem** [comment]
this is really great. But how would this help with issues #6 and #7. I understand that this PR only generates a JAR file

**Comment by pupper68k** [comment]
I have integrated a launch4j plugin that allows windows users to build a .exe, instructions are in readme.
The exe was tested on windows 10.

**Comment by abdalmoniem** [comment]
great, tested and approved, thank you very much

**Pull request merged**
